#!/usr/bin/env python2
"""
Compare fingerprints from fingerprint.js and fingerprint.py.

Installation:

1. git clone git@github.com:seanh/pdf.js.git
2. cd pdf.js
3. git checkout fingerprint
4. npm install
5. npm install estraverse
6. gulp dist-install
7. Create a new Python virtual environment
8. Install PDFMiner from git (because the version on PyPI is out of date and
   missing AES v2 decryption support):

     pip install git+https://github.com/euske/pdfminer.git

Usage:

    ./compare-fingerprints files_to_compare/*.pdf

"""
import subprocess
import sys


for pdf in sys.argv[1:]:

    # Get the fingerprint from PDF.js.
    try:
        js_fingerprint = subprocess.check_output(['./fingerprint.js', pdf])
    except subprocess.CalledProcessError:
        # Skip files that PDF.js can't parse.
        continue

    # Get the fingerprint from Python.
    try:
        py_fingerprint = subprocess.check_output(['./fingerprint.py', pdf])
    except subprocess.CalledProcessError:
        print "Fail: " + pdf
        continue

    matches = js_fingerprint == py_fingerprint

    # Strip newlines before printing.
    js_fingerprint = js_fingerprint.strip()
    py_fingerprint = py_fingerprint.strip()

    if matches:
        print "Match: " + js_fingerprint
    else:
        print "Mismatch. File: " + pdf + " PDF.js: " + js_fingerprint + " Python: " + py_fingerprint
